### ISSUE TITLE
Jolly Mec - Network timeout issue

### ISSUE THREAD

**Issue by Slavitacus** [securechicken/homebridge-micronova-agua-iot-stove#2]
## Environment and Input

|Item|Your information|
|---|---|
|**Homebridge Version**|1.3.3|
|**Plugin version**|0.0.1-alpha.3|
|**Stove brand/mobile app name**|Jolly Mec|
|**iOS version**|N/A|

### Expected function and references
I have timeout messages, and the pluging is not responding
### Bug
`3/10/2021, 7:54:31 AM] [Poêle Chalet Taroko] _updateCharacteristicsValues failed: _updateAPIRegistersData API request failed: network timeout at: https://jollymec.agua-iot.com/deviceGetBufferReading`

### Steps to Reproduce

1.
2. ...

### Ideas
I don't know how the pluging works, but it seems the server Agua IOT isn't very reliable (I also sometimes can't connect with the Jolly Mec APP), so maybe the pluging should still try to connect until he got respond form the server .... I don't know if its a good idea or not, and if its possible or not...

**Comment by securechicken** [comment]
Thanks for reporting and helping developing this plugin!

There is an hardcoded timeout of 5 seconds for HTTP requests (which, network wise, is quite long already), and if the server does not reply within such delay, the request will fail. It it fails at plugin init, then the plugin will not start (there is no point going on without required data from API on heater settings and so, the plugin can't work without such). I believe that the specific API endpoint for your heater, your Homebridge system network connection, or your Internet connection bandwidth/latency might be causing such a long delay.

In any case, the plugin should however try again. The timeout value could also be made bigger. But I'm afraid either of these solutions will bring unwanted side effects (like Homebridge complaining the plugin is slow), and none will fix the root cause of the issue (an HTTP request taking more than 5s to complete... we may retry or wait longer, but at some point the plugin cannot work without API provided data).

While I try to find a solution for this case, could you please start testing options by using a longer HTTP timeout, and tell if it works better:

- On your Homebridge system shell (I assume this is a GNU/Linux system), type the following command as a privileged user (type this as root without the 'sudo' prefix if you don't have sudo): `sudo sed -i 's/HTTP_TIMEOUT = 5000/HTTP_TIMEOUT = 10000/' /usr/lib/node_modules/homebridge-micronova-agua-iot-stove/index.js`
- Check that it worked by typing such command then: `grep 'HTTP_TIMEOUT = 10' /usr/lib/node_modules/homebridge-micronova-agua-iot-stove/index.js`. You should see a result line which starts with `const HTTP_TIMEOUT = 10000;`. If not, well come back here showing your shell results :) 
- Restart Homebridge (or the plugin child bridge only if you set one up).

**Comment by Slavitacus** [comment]
Hi, sorry for the delay.
so I did it, I have this answer:
`/homebridge # grep 'HTTP_TIMEOUT = 10' /homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js`
`const HTTP_TIMEOUT = 10000; // 5s in ms, the web service is somehow laggy`

when I restart the child bridge i have this issue:
`[3/14/2021, 9:49:48 AM] [Poêle Chalet Taroko] _updateCharacteristicsValues failed: _waitForRegistersDataReadJobResult API job failed: _getAPIJobResult API request failed: request to https://jollymec.agua-iot.com/deviceJobStatus/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx failed, reason: getaddrinfo EAI_AGAIN jollymec.agua-iot.com`

**Comment by securechicken** [comment]
Hi and thanks for feedback.
There is absolutely no issue with delay, take the time you want!

So it means the reported error did not happen again (as the new request that is failing come later during the process) - raising timeout might have been enough for you.

As for the new error that appears : it is not due to the plugin, but to your Homebridge underlying system not being able to resolve the Internet hostname `jollymec.agua-iot.com`. There is nothing the plugin can do about that (except retrying.. but still, the plugin will not work while the API hostname can't be resolved) : it means there are general network / Internet connectivity issues at your Homebridge system, or that the remote API name servers are down (which does not seem to be the case right now - be aware though that some Micronova APIs are undergoing maintenance for more than a full day these days). This could be temporary only.

Do you have any other Homebridge plugins running that rely on Internet access? Are there similar errors with them? If so I would advise to check and troubleshot the Internet connectivity from your Homebridge server, with various network connectivity tests, such as measuring bandwidth and latency with tools like `ping`,  `speedtest-cli`, and checking correct DNS resolutions with `nslookup jollymec.agua-iot.com` (if the later successfully returns an IP address, which seelms to be `178.33.104.139`, then restart the child bridge and it should work).

In any case, I'll implement longer HTTP timeout delays and retries in a later release, so that such network connection issues will cause the plugin to retry until it can reach the API (but still, no connection to API, no working plugin meanwhile...).

**Comment by securechicken** [comment]
Should be better (infinite retries while there are network issues, till it works again + longer timeouts) with 0.0.1-beta.1.
You will stil have error messages (something is going wrong network-side), and plugin still won't work while not connected to API, but you won't have to restart plugin/Homebridge for it to work when network is up again.
Feel free to reopen if same bug appears.

**Comment by Slavitacus** [comment]
Okay, thank you very much :-)

**Comment by Slavitacus** [comment]
Hi, 
I think my internet connection My internet connection is probably not good because I have this kind of issues with an other plugin who need internet... 
But since your update, your plugin try until it connect, it’s perfect! Thank you very much for your efficiency!
