### ISSUE TITLE
Jolly Mec - Fan Rotation Speed stepp range issue

### ISSUE THREAD

**Issue by Slavitacus** [securechicken/homebridge-micronova-agua-iot-stove#4]
## Environment and Input

|Item|Your information|
|---|---|
|**Homebridge Version**|1.3.3|
|**Plugin version**|v0.0.1-beta.1|
|**Stove brand/mobile app name**|Jolly Mec|
|**iOS version**|iOS 14.5|

### Expected function and references
I have unmatch issues between Apple Home App, and the Stove.
So I understand that the plugin is reporting REAL current power to HomeKit/Homebridge, not the user set power, but I have a mismatch between the speed power that I can set and the information back from the stove
For exemple if the stove is running speed 1, I will have speed 3 in the Home App.
If the stove is running Eco, I will have speed 1 in the Home App.
If the stove runing speed 1, It will be speed 3 in the App, but if i want to set it on speed 3, I have an issue, its already on 3....

My stove got 7 speeds (the power is set with the speed):

Eco = super slow fans speed, super slow fire
Silence = slow fan speed, slow fire
1 = speed 1 fan, 1 power fire
2 = speed 2 fan, 2 power fire
3 = speed 3 fan, 3 power fire
4 = speed 4 fan, 4 power fire
5 = speed 5 fan, 5 power fire

so I thought if its possible of course to match the stove speed/power with the Home App:

Silence = fan speed 0 on the App
1 = fan speed 1 on the App
2 = fan speed 2 on the App
3 = fan speed 3 on the App
4 = fan speed 4 on the App
5 = fan speed 5 on the App

and off course, the invers, if we set the App on a speed, the stove follow it:

Fan speed 0 on the App = it send the request Silence (like i set it from the stove remote)
Fan speed 1 on the App = it send the request speed 1 (like i set it from the stove remote)
Fan speed 2 on the App = it send the request speed 2 (like i set it from the stove remote)
Fan speed 3 on the App = it send the request speed 3 (like i set it from the stove remote)
Fan speed 4 on the App = it send the request speed 4 (like i set it from the stove remote)
Fan speed 5 on the App = it send the request speed 5 (like i set it from the stove remote)

I'm not sure my explaination is clear...
I'll put tabs to explain.

<img width="555" alt="Capture d’écran 2021-03-14 à 21 19 14" src="https://user-images.githubusercontent.com/77431510/111082879-f1555280-850a-11eb-9516-7a0328b4d3c0.png">

I don't know if its clear, and I don't know if it even possible...

I hope I'm not too boring...

Thank you very much.

### Steps to Reproduce

1.
2. ...

**Comment by securechicken** [comment]
Hi,

Will make the plugin reports user set power instead of real stove power, to fix the case where reported power might actually "override" a target power user would like to set with HomeKit.
This might fix some cases for your specific stove model.

As for the the rest of it, it seems your stove might be actually using stove powers as special mode settings, which this plugin will not be able to implement, as this would need a specific custom implementation of power handling for all stove models, where the power slider in HomeKit would mean a different thing for each stove brand/model. Let's see...

In order to check what is the extend of the specifics for your stove brand/model, I would need you to activate plugin debug mode (now there is a simple "Debug" checkbox in plugin config, to get debug logs for the plugin only : check it and restart child bridge or whole Homebridge); and reports:
- the full list of the registers map for your stove, shown shortly after init, looking like this: `[DEBUG] _getAPIStoveRegistersMap apiStoveRegisters: alarms_enable,alarms_get,allarme_desc_get,calendar_day_get,calendar_day_set,calendar_day_week_get,calendar_day_week_set,calendar_month_get,calendar_month_set,calendar_year_get,calendar_year_set,chrono_p1_day_friday_set,chrono_p1_day_monday_set,chrono_p1_day_saturday_set,chrono_p1_day_sunday_set,chrono_p1_day_thursday_set,...`
- the full list of registers offsets/names map, looking like this, and shown just after the previous:
```
[DEBUG] 21 => alarms_enable
[DEBUG] 51 => alarms_get
[DEBUG] 32992 => allarme_desc_get
[DEBUG] 33019 => calendar_day_get,calendar_day_set
[DEBUG] 33016 => calendar_day_week_get,calendar_day_week_set
[DEBUG] 33020 => calendar_month_get,calendar_month_set
[DEBUG] 33021 => calendar_year_get,calendar_year_set
...
```
- some examples of power change/get debug logs, looking like this: `[DEBUG] _getStoveRegister power_set: {"_v":3,"reg_type":"SET","offset":32895,"formula":"#","formula_inverse":"#","format_string":"{0}","set_min":1,"set_max":4,"mask":255}`

Thanks!

**Comment by Slavitacus** [comment]
Hello,

Is it ok?

`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] _getAPIStoveRegistersMap apiStoveRegisters: alarms_get,calendar_day_set,calendar_day_week_set,calendar_month_set,calendar_year_set,canalization_1_enable,canalization_1_set,canalization_1_temp_air_enable,canalization_1_temp_air_set,Canalization_1_vent_enable,Canalization_1_vent_set,canalization_2_enable,canalization_2_set,canalization_2_temp_air_enable,canalization_2_temp_air_set,canalization_2_vent_enable,canalization_2_vent_set,chrono_general_enable_set,chrono_p1_day_friday_set,chrono_p1_day_monday_set,chrono_p1_day_saturday_set,chrono_p1_day_sunday_set,chrono_p1_day_thursday_set,chrono_p1_day_tuesday_set,chrono_p1_day_wednesday_set,chrono_p1_power_set,chrono_p1_start_set,chrono_p1_stop_set,chrono_p1_temperature_set,chrono_p2_day_friday_set,chrono_p2_day_monday_set,chrono_p2_day_saturday_set,chrono_p2_day_sunday_set,chrono_p2_day_thursday_set,chrono_p2_day_tuesday_set,chrono_p2_day_wednesday_set,chrono_p2_power_set,chrono_p2_start_set,chrono_p2_stop_set,chrono_p2_temperature_set,chrono_p3_day_friday_set,chrono_p3_day_monday_set,chrono_p3_day_saturday_set,chrono_p3_day_sunday_set,chrono_p3_day_thursday_set,chrono_p3_day_tuesday_set,chrono_p3_day_wednesday_set,chrono_p3_power_set,chrono_p3_start_set,chrono_p3_stop_set,chrono_p3_temperature_set,chrono_p4_day_friday_set,chrono_p4_day_monday_set,chrono_p4_day_saturday_set,chrono_p4_day_sunday_set,chrono_p4_day_thursday_set,chrono_p4_day_tuesday_set,chrono_p4_day_wednesday_set,chrono_p4_power_set,chrono_p4_start_set,chrono_p4_stop_set,chrono_p4_temperature_set,chrono_week_enable_set,clock_hour_set,clock_minute_set,power_set,real_power_get,standby_get,standby_set,status_get,status_managed_get,status_managed_off_enable,status_managed_on_enable,temp_air_get,temp_air_set,temp_gas_flue_get,w_p_braciere_enable,w_p_braciere_get,w_spegnimento_enable,w_spegnimento_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 93 => alarms_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33019 => calendar_day_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33016 => calendar_day_week_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33020 => calendar_month_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33021 => calendar_year_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32853 => canalization_1_enable,canalization_1_temp_air_enable,Canalization_1_vent_enable,canalization_2_enable,canalization_2_temp_air_enable,canalization_2_vent_enable`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32974 => canalization_1_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32973 => canalization_1_temp_air_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32975 => Canalization_1_vent_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32977 => canalization_2_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32979 => canalization_2_temp_air_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32978 => canalization_2_vent_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32894 => chrono_general_enable_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32919 => chrono_p1_day_friday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32915 => chrono_p1_day_monday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32920 => chrono_p1_day_saturday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32921 => chrono_p1_day_sunday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32918 => chrono_p1_day_thursday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32916 => chrono_p1_day_tuesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32917 => chrono_p1_day_wednesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32913 => chrono_p1_power_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32911 => chrono_p1_start_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32912 => chrono_p1_stop_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32914 => chrono_p1_temperature_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32930 => chrono_p2_day_friday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32926 => chrono_p2_day_monday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32931 => chrono_p2_day_saturday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32932 => chrono_p2_day_sunday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32929 => chrono_p2_day_thursday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32927 => chrono_p2_day_tuesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32928 => chrono_p2_day_wednesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32924 => chrono_p2_power_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32922 => chrono_p2_start_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32923 => chrono_p2_stop_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32925 => chrono_p2_temperature_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32941 => chrono_p3_day_friday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32937 => chrono_p3_day_monday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32942 => chrono_p3_day_saturday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32943 => chrono_p3_day_sunday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32940 => chrono_p3_day_thursday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32938 => chrono_p3_day_tuesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32939 => chrono_p3_day_wednesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32935 => chrono_p3_power_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32933 => chrono_p3_start_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32934 => chrono_p3_stop_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32936 => chrono_p3_temperature_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32952 => chrono_p4_day_friday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32948 => chrono_p4_day_monday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32953 => chrono_p4_day_saturday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32954 => chrono_p4_day_sunday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32951 => chrono_p4_day_thursday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32949 => chrono_p4_day_tuesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32950 => chrono_p4_day_wednesday_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32946 => chrono_p4_power_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32944 => chrono_p4_start_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32945 => chrono_p4_stop_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32947 => chrono_p4_temperature_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32910 => chrono_week_enable_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33017 => clock_hour_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33018 => clock_minute_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32976 => power_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 69 => real_power_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33095 => standby_get,standby_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 33 => status_get,status_managed_off_enable,status_managed_on_enable`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 232 => status_managed_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 20 => temp_air_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 32875 => temp_air_set`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 2 => temp_gas_flue_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] 784 => w_p_braciere_enable,w_p_braciere_get,w_spegnimento_enable,w_spegnimento_get`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] _getStoveRegister power_set: {"_v":null,"reg_type":"SET","offset":32976,"formula":"#","formula_inverse":"#","format_string":"{0}","set_min":0,"set_max":5,"mask":65535}`
`[3/15/2021, 7:45:35 AM] [Poêle Chalet Taroko] [DEBUG] _getStoveRegisterBoundaries power_set => [0, 5]`
`[3/15/2021, 7:45:36 AM] [Poêle Chalet Taroko] [DEBUG] _getStoveRegister real_power_get: {"_v":2,"reg_type":"GET","offset":69,"formula":"#","formula_inverse":"#","format_string":"{0}","set_min":0,"set_max":5,"mask":255}`
`[3/15/2021, 7:45:36 AM] [Poêle Chalet Taroko] [DEBUG] _getStoveRegisterValueFromCache real_power_get => 2`
`[3/15/2021, 7:45:36 AM] [Poêle Chalet Taroko] [DEBUG] _updateCharacteristicsValues RotationSpeed: 2, (ERR: null)`

Thanks,

**Comment by securechicken** [comment]
Perfect (I edited to keep relevant parts only).
So it seems that your stove/brand model is not using power setting in a different way that I knew of after all.
There are 5 levels of "power", and 0 is OFF. Apart from the issues you have and that are due to the fact plugin is reporting real power instead of set power (will be changed), it is just that your official app may be showing Silent and Eco modes in the same place than power levels, but these are different things. 

I think that the plugin should not set modes and power levels with the same power slider. This would be confusing, and not all stoves may have such modes. Setting stove modes is also not in the scope of this plugin functionalities for now. This would be doable, but would require a lot of tests to see which stove brand/model implement such modes, and what is the specific implementation (register names and values) for each. It would also require to expose additional devices controls on HomeKit with dedicated buttons to set modes, as the HeaterCooler device from HomeKit does not have such concept as "modes" settings for now.

**Comment by Slavitacus** [comment]
Hello, 

Silence is also a level of power:
Silence, 1, 2, 3, 4 and 5
On the other and, Eco is indeed an other thing, It can’t be set by user, it the stove mode when the set temperature is reached.

https://user-images.githubusercontent.com/77431510/111210170-380b8100-85cd-11eb-9930-310b2516a22d.MP4

So I woud like to know if it's possible to use the level 0 for Silence and not switching off the stove?

Thanks,

**Comment by securechicken** [comment]
Everything is doable, but this specific feature of the HomeKit Fan Slider "0" value ordering a specific stove model to go into "Silence" mode won't be done by me with this plugin for the time being, as explained in the previous message. It will be considered again if with time, it is discovered that most (if not all) of Micronova Agua controlled stoves also have a "Silence" mode, and that there is a way to discover the setting to be set in stove to enable Silent mode (see later: this is NOT a power level).

Then, it's not because the official specific app for the stove shows the "Silence" mode in the power level setting widget as first position, that the "Silence" is actually a power level which is 0 in stove. This is just an app design interface layout.

As can be read from the Micronova module directly for your stove (from debug messages), the stove has power level from 0 to 5, and putting power level to 0 sets the stove OFF. This is not the plugin deciding that; this is the stove which turns itself OFF when it receives the order to set the power level to 0. Then we also could observe already that when your stove is in "Silence" mode, the corresponding real power level in stove is actually 2 (not 0). This is also the stove deciding to set the power level to 2 when it's put in "Silence" mode - not the plugin. What the stove does in "Silence" mode is actually setting the power level to 2 and cutting the air ventilation OFF. So power level 0 is NOT the same than "Silence" mode, as you could think because of the official app layout. Setting the stove to "Silence" mode requires to change one (or several) special values in Micronova controller/stove which is not the power level, but maybe one of "w_p_braciere_enable" or "w_spegnimento_enable" for your specific stove model.

**Comment by Slavitacus** [comment]
Okay, I understand, thank you taking time explaining it !

**Comment by brufal** [comment]
@Slavitacus Bonjour à toi, en regardant ta petit vidéo, il m'a semble comprendre que tu devais parler français car ton application JollyMec semble être en française.

est ce que tu serai me renseigner?

Merci d'avance de ton retour.

I hope your speak french, i think when i was looking your short screenvideo, your app jolly mec lookslike in french.

i need your help if you can ;-)
